### ISSUE TITLE
GetUserByID(0)能返回UserID=1的那个用户

### ISSUE THREAD

**Issue by ZM-J** [Chun-Ge/Shudong-Backend#104]
不知道为什么……总之**静态审查**代码是没错的……
估计是**xorm**的锅

下面是有两个数据项 对GetUserByID(-1..5)的测试结果：
-1 32 &{-1   0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC}
0 32 &{1 1184862561@qq.com 202cb962ac59075b964b07152d234b70 2018-06-24 19:29:52 +0800 CST 2018-06-24 19:29:52 +0800 CST}
1 32 &{1 1184862561@qq.com 202cb962ac59075b964b07152d234b70 2018-06-24 19:29:52 +0800 CST 2018-06-24 19:29:52 +0800 CST}
2 32 &{2 7777777@qq.com b4aa00bc1c59b9d1cdd07479070e355e 2018-06-24 19:29:52 +0800 CST 2018-06-24 19:29:52 +0800 CST}
3 32 &{3   0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC}
4 32 &{4   0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC}
5 32 &{5   0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC}
可以看到 GetUserByID(0)与GetUserByID(1)的结果是一样的……

**Comment by MarshallW906** [comment]
感谢提醒，具体原因不确定，不过暂时先搁置吧。目前整个系统都没有太多处理无效输入和非法输入的代码，原来想要尽量完成这一部分，后来发现这部分的工作量会非常大，最终还是选择优先开发功能。

目前对于GetUserByID的正常用例是前端调用`RetrieveUserInfo`，正常情况下，后台通过这种方式只会执行`userid>=1`的用户查询，至于0和负数userid，在预期运行过程中不会出现。

不过确实需要考虑很多这方面的问题。这也是Critical问题中的一个，会先记下来。
