### ISSUE TITLE
无法解决跨域问题, 因而 login 等 API 前端无法调用

### ISSUE THREAD

**Issue by Binly42** [Chun-Ge/Shudong-Backend#105]
我没怎么看后端的代码, 但是我尝试过一些方式来解决, 均无效, 不知是哪里有问题?

- 直接使用 `app.Use(cors.AllowAll())`
- 手动设置:
```
app.UseGlobal(func(ctx iris.Context) {
	ctx.Header("Access-Control-Allow-Origin", "*")
	ctx.Next()
})
```

以上两种方式, 均是直接接在 `app := iris.New()` 后, 均无效, Chrome 中的 log 如下:

> OPTIONS http://localhost:8000/login 405 (Method Not Allowed)

> Failed to load http://localhost:8000/users: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 405.

我怀疑是否因为 `Method Not Allowed` 所以预请求失败 ?

---

也试过 [Using application/x-www-form-urlencoded format](https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format) 以试图绕过这个坑, 依然失败, log 如下:

> POST http://localhost:8000/login 400 (Bad Request)

> Failed to load http://localhost:8000/login: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

这次确实没有预请求了, 然而还是 CORS 失败 ...

@MarshallW906 , @liangtj

**Comment by MarshallW906** [comment]
大概懂了，是后端返回的Response Header里没有加`Access-Control-Allow-Origin`。
晚一点加上。

**Comment by Binly42** [comment]
这一点是肯定的了 (疏忽了, 之前都忘了端口不同也是要跨域的 ...), 我只是疑惑为啥我改了代码但是没有效果 ... 不知道会不会是不是后端的代码还有什么别的地方会对 Response Header 作改动?

我现在还在赶 lesson16 的那个团队 ECB 图的锅, 先没法管这个了不好意思 ... (

**Comment by MarshallW906** [comment]
#106 已在所有Response中都加入`Access-Control-Allow-Origin`。

**Comment by Binly42** [comment]
还是不行 ...

其实我感觉 你 merge 的这个 和我试过的第一种方法也许除了代码组织形式上之外没啥区别 ... (

我想按我之前的思路找找看有没解决方案:
- 可能因为后端没有对 Options 方法做支持, 所以所有的预请求全都被 `405 (Method Not Allowed)` 掉, 也就没有然后了 ?
- 可能因为后端强制要求请求为 json 所以当我尝试 [Using application/x-www-form-urlencoded format](https://github.com/axios/axios#using-applicationx-www-form-urlencoded-format) 这种方法的时候则直接被判断 `400 (Bad Request)`, 所以也没有然后 ... ?

话说能说下怎么控制 log 的 level 吗? 我看现在默认的 log 都好简洁 ... 应该有 debug mode 之类的吧 ?

**Comment by Binly42** [comment]
我终于知道为什么我的尝试总是失败了 ... 

你们写了两个初始化 server 的函数 .... 而我改代码的地方总是 `server.Start`, 然而默认情况下代码跑起来执行的是 `server.StartWithConfiguration` ..... 我之前先入为主了 .......

---

我现在可以通过 `app.Party("/", cors.AllowAll()).AllowMethods(iris.MethodOptions)` 的方式包一个 Party, 用这个 Party 来注册的 API 可以正常相应 Options 请求了 ... 但是 Party 的类型 和 Application 冲突, 我待会先试着适配一下试试 ;

另外, 我之前两个猜想似乎相辅相成了, 默认的预请求无类型, 成功地被 `CheckContentTypeJSON` 拦截了 ...

我待会会找时间再看看, 我估计应该能绕过去了 ;

**Comment by Binly42** [comment]
#107 可以绕过去了

**Comment by MarshallW906** [comment]
我才反应过来你对login用的是OPTIONS。。 这个是有什么讲究吗，文档里写的login是用POST

（总之我先merge吧 一会可能要出去 没法一直在电脑前

@Binly42 已合并

**Comment by Binly42** [comment]
噢 这个是 预请求(`preflight request`) 呀, 跨域的时候某些情况下浏览器自动发出的 ;

**Comment by MarshallW906** [comment]
ok。。 不过看你pr里又把Access-Control-Allow-Origin的header又给去掉了 所以其实不加这个也行？

**Comment by MarshallW906** [comment]
ok。。 不过看你pr里又把Access-Control-Allow-Origin的header又给去掉了 所以其实不加这个也行？

**Comment by Binly42** [comment]
不加哪个? ... (

我 pr 里把你之前加的那个去掉, 是因为 报错 说 `Access-Control-Allow-Origin` 的值只能是一个 ... 我就想着全让 iris 提供的 cors 包来处理就好 ...

**Comment by MarshallW906** [comment]
oh 懂了 我以为cors包里没有这个， 那就都清楚了。。
