### ISSUE TITLE
个别 API 与 apiary 文档中的描述不一致

### ISSUE THREAD

**Issue by Binly42** [Chun-Ge/Shudong-Backend#108]
`Retrieve User Info` API 在后端代码里是: https://github.com/Chun-Ge/Shudong-Backend/blob/55ea8097694305da6c2093533e0e73b68b8389a7/vendor/route/route.go#L27 ;
与 [apiary 文档](https://chungeshudong.docs.apiary.io/#reference/user/user-operations/retrieve-user-info) 上不符 ;

( 这行代码缩进好像有问题, 大概是没注意到的错漏 ...

**Comment by MarshallW906** [comment]
用后端代码里的。 userId在jwt里就有，所以不需要额外指定路由，api文档没更新→_→ 晚点改

**Comment by Binly42** [comment]
`Get recent posts` API 返回的结果中, 在各 post 对象里有属性 `postid`, 

而在 [apiary 文档](https://chungeshudong.docs.apiary.io/#reference/post/post-collection/get-recent-posts) 上 属性名为 `postId` ...

**Comment by MarshallW906** [comment]
#109 RetrieveUserInfo 文档已更新， apiary与本地apiary.apib内容均同步更新。

**Comment by MarshallW906** [comment]
`GetRecentPosts`属性名问题已修复。 #110
