### ISSUE TITLE
后端的 `CheckContentTypeJSON` 检查过强, 与一些 API 冲突

### ISSUE THREAD

**Issue by Binly42** [Chun-Ge/Shudong-Backend#111]
比如: [`Delete a post` API](https://chungeshudong.docs.apiary.io/#reference/post/get-and-delete-post/delete-a-post) 没有请求体, 也便没有标注类型, 这样就会被拦下 ... 之前 Options 方法也是类似的情况 ...

我现在用来对接测试的话, 就只是简单地修改一下它的判断条件即可, 然而我感觉或许更好的做法需要一些重构? 所以我就先不推 PR 了 ...

**Comment by MarshallW906** [comment]
ok 
也可以路由分配那里手动指定需要checkJSON的路由

**Comment by MarshallW906** [comment]
放行了DELETE #117
