### ISSUE TITLE
`Like` API 似乎没有成功对数据库写入数据 (两个都是)

### ISSUE THREAD

**Issue by Binly42** [Chun-Ge/Shudong-Backend#112]
它们响应的结果都是合理的, 即使两个用户各自操作也没问题, 但是数据库中 post 表 和 comment 表中的 like 
 字段 却一直为 0 ...

**Comment by MarshallW906** [comment]
entity多了一个like字段…… 那个like字段从来都没用过。
真正计数是在`user_upvote_post`表里面使用count
调用获取post信息的时候，应该是可以看到正常的count数吧。。

**Comment by MarshallW906** [comment]
如果response里的count数是正常的话这个先不改了……
