### ISSUE TITLE
建议往 `Get recent posts` API 的返回结果中的 post 对象中添加 `currentUserLike` 属性

### ISSUE THREAD

**Issue by Binly42** [Chun-Ge/Shudong-Backend#113]
便于在获取到 post 后进行的一些细节渲染

---

其实好像也就那样, 不是啥关键逻辑, 要不就给搁置了吧, 反正也 DDL 了 ... (我这个对接来得太晚了

**Comment by MarshallW906** [comment]
行，那如果不是很critical的东西就先不管了，，，我把其他大作业都做完了再回来改
