### ISSUE TITLE
Travis-CI keeps failing

### ISSUE THREAD

**Issue by MarshallW906** [Chun-Ge/Shudong-Backend#15]
I enabled the connection with `travis-ci` yesterday and it just keeps raising errors like the following.

But there's nothing wrong when I run `go build` on my local command prompt, and I can still get the binary (named as `Shudong-backend`).
```text
import "context": import path doesn't contain a slash
package context: unrecognized import path "context"
import "entity": import path doesn't contain a slash
package entity: unrecognized import path "entity"
import "err": import path doesn't contain a slash
package err: unrecognized import path "err"
```

**Comment by alexandrali3** [comment]
Solved. See #19.
I fixed it by adding quotation marks to version of language
```
go:
  - "1.10"
```
It seems quite tricky that if no quotation mark is added to `1.10` in the language version field, it will be parsed as "1.1". XD.

**Comment by MarshallW906** [comment]
Thanks a lot!
