### ISSUE TITLE
Finalize Restful API Design

### ISSUE THREAD

**Issue by MarshallW906** [Chun-Ge/Shudong-Backend#2]
- 登入/登出问题： 目前的文档里登入/登出的API设计存在问题
  - 一个想法是单独出/login /logout两个API，不过这样就不完全是面向资源了（但看起来直观，github采用这种）
  - 另一个想法是 /users 用POST上username&password代表登陆，DELETE代表登出（目前是这样，但感觉好别扭）
- authentication： 目前文档里使用的是简单的url中(或form中)附带token的方式，改为cookie模式，需要修改
@Boyce-Lee @alexandrali3 @liangtj @VinaLx

**Comment by Binly42** [comment]
就依你们后端的决定吧。。。

但是我觉得有个问题是，即使是纯的 REST 的 登录登出，资源应该都是 session 吧。。。

**Comment by liangtj** [comment]
emmm，restful api本身就是通过规范来减少沟通成本，对于登陆登出，如果采用2，反而显得不直观，甚至意味不明带来沟通成本上升。。。个人赞成方案1，直观了当,  而且通用的登陆登出基本只见过/login/logou,~~没必要不因地制宜一五一十遵守死规范？？~~（GG，留下了没技术的泪水.jpg， 你们随意就好，个人无所谓

**Comment by MarshallW906** [comment]
抱歉我才看到你们的comment。。

**Comment by Boyce-Lee** [comment]
老哥，login的get方法的文档说明好像漏了哇

**Comment by MarshallW906** [comment]
@Boyce-Lee Login不需要get吧。。 post上用户名密码即可
#8 这里是注册 以及上周末讨论的登陆模式

**Comment by Boyce-Lee** [comment]
用户第一次登陆时候填表单的那个html，不是get -> 登陆.html -> 填好user、password的表单 -> post  这样吗？

**Comment by MarshallW906** [comment]
html不需要后台返回 我们只要完成api就行了

**Comment by Boyce-Lee** [comment]
get！

**Comment by MarshallW906** [comment]
所以我们UserId用哪个。。 一个是表里的主键， 或者auto-generated

我正在修改`entity.User`的结构和写一些基本model层，写完会发PR

**Comment by MarshallW906** [comment]
暂时直接用主键ID吧。 我看到外键里用的是id

**Comment by MarshallW906** [comment]
考虑增加单独的API 获取post/comment的点赞量 （暂时Low priority 主体基本完成了再考虑）

**Comment by Boyce-Lee** [comment]
+ category这个信息，前后端之间交互的是name，而不是id。
+ category name 和id之间的映射是数据库维护的，name应该是unique。
+ 前端需要知道所有的category name， 后端需要提供相应的查询api
+ 后端通过与数据库交互，通过category name获取对应的id，用于比如createpost等业务逻辑
