### ISSUE TITLE
I'm afraid I don't know how to use jwt for authentication .....

### ISSUE THREAD

**Issue by MarshallW906** [Chun-Ge/Shudong-Backend#32]
@Boyce-Lee @alexandrali3 
I just put some simple lines at the beginning of the 2 funcs (`UpvotePost()` & `UpvoteComment()`), assuming that it will have been checked with both `userid` & `postid`/`commentid` being `1` ....

Could you pls give me some examples....?

**Comment by alexandrali3** [comment]
See the CheckLoginStatus handler in [middlewares/jwt.go](https://github.com/Chun-Ge/Shudong-Backend/blob/dev/vendor/middlewares/jwt.go). It is a middleware handler which checks user's login status. If no token of login information is found, error msg `Unauthorized` will be raised, and no further actions will be performed.

Therefore, there is no need of you to do anything with JWT authentication, beside adding the handler `middlewares.CheckLoginStatus` in the registration of your routers. Take "logout" as a simple example:
```
app.Post("/logout", middlewares.CheckLoginStatus, service.UserLogout)
```

FYI, I have added some useful comments to the functions and handlers in the customized JWT middleware, which, I believe, will solve most of your confusion. Check them under the dev branch. :D

[middlewares](https://github.com/Chun-Ge/Shudong-Backend/tree/dev/vendor/middlewares)

**Comment by MarshallW906** [comment]
Thanks very much again!
