### ISSUE TITLE
command params

### ISSUE THREAD

**Issue by MarshallW906** [Chun-Ge/Shudong-Backend#69]
I've had a thought on the design(usage) of `cobra` command params.

- -p, —port : specify the port that the server will be attached to.
- --mysql-port : specify the port that the mysql-server-side is running on.
- --mysql-user: specify the username for mysql
  - OR: asks for mysql’s username & password at the beginning of the runtime?
- -c --config : specify a config file that provides params required above
  - maybe we need a YAML parser

@Boyce-Lee What do u think of it?

**Comment by Boyce-Lee** [comment]
mysql-password, and the url of the mysql

**Comment by MarshallW906** [comment]
Cobra command added. #76
