### ISSUE TITLE
SQL Injection Prevention

### ISSUE THREAD

**Issue by Boyce-Lee** [Chun-Ge/Shudong-Backend#79]
# something remains to be cheked
+ can all apis prevente sql-injection, if not, find the bugs
+ Xorm support sql-injection prevention?
+ replace form with json in http request body, is a good way to escape sql-injection cases like jnjecting ' or ". However, does it work well for any cases? or most cases?

**Comment by MarshallW906** [comment]
`go-xorm` has already provided a injection-prevention built-in  module by [xorm/builder](github.com/go-xorm/builder). So.. we can still trust it until something is wrong as we don't have too much time left to get this project done.
