### ISSUE TITLE
Is the api `Change Password` redundant ?

### ISSUE THREAD

**Issue by Binly42** [Chun-Ge/Shudong-Backend#80]
I found that requests would be with the Authorization info for `Change Password`, which maybe means it is used to let users do that initiatively. However, I don't think `Change Password` is different enough from `Modify User Info` ...

Is there any reason why we need such an api ?

**Comment by MarshallW906** [comment]
#81 .
3 APIs are removed.

**Comment by MarshallW906** [comment]
Now changing password is only approached by `PATCH /users/password` or `PATCH /reset_password`. See the api doc FYI.
